spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: google-client-id
            clientSecret: google-client-secret
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true